import type { Metadata } from "next";
import "./globals.css";

import { Prompt } from "next/font/google";
const prompt = Prompt({ weight: "100", subsets: ["latin", "thai"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="th" className="text-white">
			<body className={prompt.className}>{children}</body>
		</html>
	);
}
